### PR TITLE
Update codejam-the-gem-puzzle.md

### PR DESCRIPTION
**Pull request by NickFallman**
Tiles can be previous, next, above, below to the empty cell. But near - is near (neighbour). )

### CODE REVIEW

**Comment by helenakrasnova** [comment]
I guess both sentences have exactly the same meaning

**Comment by NickFallman** [comment]
> @NickFallman I guess both sentences have exactly the same meaning

Tiles can be previous, next, above, below to the empty cell. But near - is near (neighbour). )

**Comment by valerydluski** [comment]
> Tiles can be previous, next, above, below to the empty cell. But near - is near (neighbour). )

I think it’s worth just writing (right, left, top, bottom) diagonally also nearby

**Comment by NickFallman** [comment]
> > Tiles can be previous, next, above, below to the empty cell. But near - is near (neighbour). )
> 
> I think it’s worth just writing (right, left, top, bottom) diagonally also nearby

Absolutely agree with you about diagonal cells. But "next" as in original text doesn't describe a task exactly. So, I'll try to propose new variant: "when you click on a neighbour tile to an empty cell (right, left, top, bottom), the neighbour tile moves to the empty cell". "Neighbour" or "near" doesn't matter in this context. I guess it will be right. Sorry, but if you and author had already decided that everything looks fine in the original source text, OK, I'm ready to finish the discussion.

**Comment by helenakrasnova** [comment]
> > > Tiles can be previous, next, above, below to the empty cell. But near - is near (neighbour). )
> > 
> > 
> > I think it’s worth just writing (right, left, top, bottom) diagonally also nearby
> 
> Absolutely agree with you about diagonal cells. But "next" as in original text doesn't describe a task exactly. So, I'll try to propose new variant: "when you click on a neighbour tile to an empty cell (right, left, top, bottom), the neighbour tile moves to the empty cell". "Neighbour" or "near" doesn't matter in this context. I guess it will be right. Sorry, but if you and author had already decided that everything looks fine in the original source text, OK, I'm ready to finish the discussion.

So, you can commit your new explanation, because "near" is the same as 'next' in that case

**Pull request closed without merging**
