### PR TITLE
fix: apply changes to Contacts after a change in the layout

### PR DESCRIPTION
**Pull request by stardustmeg**

### CODE REVIEW

**Comment by stardustmeg** [comment]
In the layout of Coffee House Contacts were changed to Contact us.
For it not to be confusing for the students I thought of renaming it in the requirements as well.

**Comment by valerydluski** [comment]
Please run the prettier for code formatting. I understand that it creates minor inconveniences, but it helps us maintain our materials in a uniform style.

**Comment by valerydluski** [comment]
And yes, I know that the problem is not with the files you edited. Please accept my apologies once again for this.

**Comment by stardustmeg** [comment]
I ran the prettier formatting on this document. I'm not sure it changed anything though. In any case I'm happy to try anything else to fix it.

**Pull request merged**
